const express=require("express")
const app=express()
const bodyparser=require("body-parser")
app.use(bodyparser.json())
const signup=require("./routes/createUser")
const findall=require("./routes/crud")
app.use("/",signup)
app.use("/",findall)
app.listen(3000,()=>console.log("server started"))
