const fs=require("fs")
const path=require("path")
const os=require("os")
const ut=os.uptime()
const t=os.type()
const r=os.release()
const tm=os.totalmem()
const fm=os.freemem()
console.log(fm)
const data=[{"uptime":ut,"type":t,"release":r,"totalmem":tm,"freemem":fm}]
filepath=path.join("../data","sample.json")
console.log(filepath)
dt=JSON.stringify(data)
fs.writeFileSync(filepath,dt)